version: '2'

services:
  app:
    build: app
    ports:
      - '8054:80'

    depends_on:
      - db
    env_file:
      - env/app.env
    volumes:
      - ~/Dev/redcap-source/edocs:/var/websites/redcap.medicine.wisc.edu/edocs
      - ~/Dev/php/redcap-source:/var/www/html

      - ~/Dev/php/redcap-plugins:/var/www/html/plugins/
      - ~/Dev/php/redcap-plugins:/var/websites/redcap.medicine.wisc.edu/redcap-plugins

      - ~/Dev/php/redcap-hooks/hooks:/var/www/html/hooks/
      - ~/Dev/php/redcap-hooks:/var/websites/redcap.medicine.wisc.edu/redcap-hooks

  db:
    image: mysql:5.7
    ports:
      - '3400:3306'
    env_file:
      - env/db.env
    restart: always
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-data:
    driver: local


