version: '3'

services:
  app:
    container_name: redcap_docker-app-1
    build: app
    ports:
      - '8080:80'

    depends_on:
      - db
    volumes:
      - ./redcap_source/:/var/www/app/public_html
      - /var/tmp/:/var/www/app/public_html/temp:Z
      - /var/edocs/:/var/www/app/public_html/edocs:Z

  db:
    container_name: redcap_docker-db-1
    image: mysql:5.7
    ports:
      - '3400:3306'
    env_file:
      - env/db.env
    restart: always
    tmpfs: /var/lib/mysql

  mailhog:
    container_name: redcap_docker-mailhog-1
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"
