version: '2'

services:
  app:
    build: app
    ports:
      - '8080:80'

    depends_on:
      - db
    volumes:
      - ../www/:/var/www/app/public_html

  db:
    image: mysql:5.7
    ports:
      - '3400:3306'
    env_file:
      - env/db.env
    restart: always
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-data:
    driver: local


